name: Deploy to Heroku

on:
  push:
    branches:
      - main

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
  
jobs:
  build:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:

    # Clone the repository
    - name: Checkout
      uses: actions/checkout@v2

    # Build Docker image
    - name: Docker build
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    # Push the Docker image to Heroku Container Registry
    - name: Publish
      run: |
        cd ./src/ESP.MQTT.WebApi
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
